{% set version = "6.1.0" %}

package:
  name: envisage
  version: {{ version }}

source:
  fn: envisage-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/envisage/envisage-{{ version }}.tar.gz
  md5: 544f20b5988cb361f62d1d793f8b00c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - traits
    - apptools
    - setuptools
  run:
    - python >=3.6
    - traits
    - apptools

test:
  imports:
    - envisage

about:
  home: http://docs.enthought.com/envisage/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: extensible application framework

extra:
  recipe-maintainers:
    - grlee77
