{% set version = "7.0.1" %}

package:
  name: envisage
  version: {{ version }}

source:
  fn: envisage-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/envisage/envisage-{{ version }}.tar.gz
  md5: bdb3b250e28306fddca9dbf178bde86d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - traits
    - apptools
    - setuptools
  run:
    - python >=3.6
    - traits
    - apptools

test:
  imports:
    - envisage

about:
  home: http://docs.enthought.com/envisage/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: extensible application framework

extra:
  recipe-maintainers:
    - grlee77
