{% set name = "envisage" %}
{% set version = "7.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/envisage-{{ version }}.tar.gz
  sha256: d6bb2938bbb45c4ef1766c55ed6f6c1c72b6fce70468ac9f5b0efcd1ef8c1d97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - apptools >=5.3
    - pyface
    - setuptools
    - traits >=6.2
    - traitsui

test:
  imports:
    - envisage
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://docs.enthought.com/envisage/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: extensible application framework

extra:
  recipe-maintainers:
    - grlee77
    - JaRoSchm
