{% set name = "envisage" %}
{% set version = "7.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/envisage-{{ version }}.tar.gz
  sha256: f7b1af88bf3a8fff2a9ac6e36bb48dea9929e3f612204cfe94aed62b0316c9e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - apptools
    - pyface
    - setuptools
    - traits >=6.2
    - traitsui

test:
  imports:
    - envisage
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://docs.enthought.com/envisage/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: extensible application framework

extra:
  recipe-maintainers:
    - grlee77
    - JaRoSchm
