{% set version = "4.9.0" %}

package:
  name: envisage
  version: {{ version }}

source:
  fn: envisage-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/envisage/envisage-{{ version }}.tar.gz
  md5: f1d489b8df7bc6679072d6340bd94911

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - traits
    - apptools
    - setuptools
  run:
    - python
    - traits
    - apptools

test:
  imports:
    - envisage

about:
  home: http://docs.enthought.com/envisage/
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: extensible application framework

extra:
  recipe-maintainers:
    - grlee77
